### ISSUE TITLE
Error: Invalid session seal on session.authenticate()

### ISSUE THREAD

**Issue by sheldonvaughn** [workos/workos-node#1132]
Running the following code

  ```
// Load the sealed session using the new session helper
    console.log('Loading sealed session...');
    const session = await workosAuthenticated.userManagement.loadSealedSession({
      sealedSession: sealedSession,
      cookiePassword: config.cookiePassword,
    });

    const { user, authenticated, reason } = session.authenticate();
```
    
   

Throws an error:
```
Invalid seal: undefined
/home/runner/Milla-Auth-Sandbox/node_modules/iron-session/dist/index.js:189
    throw new Error('Invalid session seal');
          ^

Error: Invalid session seal
    at parseSeal (/home/runner/Milla-Auth-Sandbox/node_modules/iron-session/dist/index.js:189:11)
    at /home/runner/Milla-Auth-Sandbox/node_modules/iron-session/dist/index.js:164:50
    at WebIronSessionProvider.<anonymous> (/home/runner/Milla-Auth-Sandbox/node_modules/@workos-inc/node/lib/common/iron-session/web-iron-session-provider.js:28:50)
    at Generator.next (<anonymous>)
    at /home/runner/Milla-Auth-Sandbox/node_modules/@workos-inc/node/lib/common/iron-session/web-iron-session-provider.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/home/runner/Milla-Auth-Sandbox/node_modules/@workos-inc/node/lib/common/iron-session/web-iron-session-provider.js:4:12)
    at WebIronSessionProvider.unsealData (/home/runner/Milla-Auth-Sandbox/node_modules/@workos-inc/node/lib/common/iron-session/web-iron-session-provider.js:27:16)
    at Session.<anonymous> (/home/runner/Milla-Auth-Sandbox/node_modules/@workos-inc/node/lib/user-management/session.js:90:60)
    at Generator.next (<anonymous>)

Node.js v20.16.0

```

Passing sealedData as the param for loadSealedSession in lieu of sealedSession does the same. SDK version is 7.27.3.

**Comment by PaulAsjes** [comment]
Closing the loop, this error happens if you don't `await` the authenticate call. Correct code would be:

```ts
const { user, authenticated, reason } = await session.authenticate();
```
