### ISSUE TITLE
Next.js 15.0.0rc.1 - Cannot find module 'node:crypto'

### ISSUE THREAD

**Issue by nirtamir2** [workos/workos-node#1142]
Hi
I upgraded to `"next": "15.0.0-rc.1",` and got the following error:
`Error: Cannot find module 'node:crypto': Unsupported external type Url for commonjs reference`

```
Error: Cannot find module 'node:crypto': Unsupported external type Url for commonjs reference
    at <unknown> (file:///Users/nirtamir/dev/news-spectator/nspec/apps/frontend/.next/server/edge/chunks/ssr/1eef0_@workos-inc_node_lib_e91dc8._.js:92:15)
    at [project]/node_modules/.pnpm/@workos-inc+node@7.21.0_express@4.21.0_next@15.0.0-rc.1_@babel+core@7.25.2_react-dom@19.0.0-r_pljhjndpizapsnrinpmvhabrfi/node_modules/@workos-inc/node/lib/common/crypto/node-crypto-provider.js [middleware] (ecmascript) (file:///Users/nirtamir/dev/news-spectator/nspec/apps/frontend/.next/server/edge/chunks/ssr/1eef0_@workos-inc_node_lib_e91dc8._.js:95:3)
    at <unknown> (file:///Users/nirtamir/dev/news-spectator/nspec/apps/frontend/.next/server/edge/chunks/ssr/edge-wrapper_a57693.js:693:27)
    at runModuleExecutionHooks (file:///Users/nirtamir/dev/news-spectator/nspec/apps/frontend/.next/server/edge/chunks/ssr/edge-wrapper_a57693.js:738:9)
    at instantiateModule (file:///Users/nirtamir/dev/news-spectator/nspec/apps/frontend/.next/server/edge/chunks/ssr/edge-wrapper_a57693.js:691:9)
    at getOrInstantiateModuleFromParent (file:///Users/nirtamir/dev/news-spectator/nspec/apps/frontend/.next/server/edge/chunks/ssr/edge-wrapper_a57693.js:624:12)
    at commonJsRequire (file:///Users/nirtamir/dev/news-spectator/nspec/apps/frontend/.next/server/edge/chunks/ssr/edge-wrapper_a57693.js:157:20)
    at [project]/node_modules/.pnpm/@workos-inc+node@7.21.0_express@4.21.0_next@15.0.0-rc.1_@babel+core@7.25.2_react-dom@19.0.0-r_pljhjndpizapsnrinpmvhabrfi/node_modules/@workos-inc/node/lib/index.js [middleware] (ecmascript) (file:///Users/nirtamir/dev/news-spectator/nspec/apps/frontend/.next/server/edge/chunks/ssr/1eef0_@workos-inc_node_lib_e91dc8._.js:6273:32)
    at <unknown> (file:///Users/nirtamir/dev/news-spectator/nspec/apps/frontend/.next/server/edge/chunks/ssr/edge-wrapper_a57693.js:693:27)
    at runModuleExecutionHooks (file:///Users/nirtamir/dev/news-spectator/nspec/apps/frontend/.next/server/edge/chunks/ssr/edge-wrapper_a57693.js:738:9)
```

**Comment by PaulAsjes** [comment]
Hey there, could you add more details like how you're using the library? Looks like you're using Next.js here, are you calling workos-node in a server action or in a client component?
